### ISSUE TITLE
Installer fails when no internet connection is present

### ISSUE THREAD

**Issue by henrycoggillcnc** [canonical/ubuntu-desktop-provision#609] opened 2024-04-09 13:37 UTC
I tried installing Noble daily (09/04/2024) in virt-manager QEMU/KVM, with the network NIC disabled.

The install failed. Log file is attached.

![noble_install_error](https://github.com/canonical/ubuntu-desktop-provision/assets/104218749/78f17e8c-3ef4-455a-b1a7-1aa5e3577c3f)

[noble_installer.log](https://github.com/canonical/ubuntu-desktop-provision/files/14919200/noble_installer.log)

**Comment by d-loose** [comment] 2024-04-09 13:45
Thanks for the report! This seems to be a duplicate of https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2060642

**Closed by d-loose** 2024-04-09 13:45 UTC
